package entity.domain;

import java.util.Objects;

import control.ReportService;
import entity.domain.enums.OpportunityStatus;
import entity.domain.enums.RequestStatus;

/**
 * Represents a Career Center Staff member in the internship placement system.
 * Extends the abstract User class.
 */
public class CareerCenterStaff extends User {
    private String staffDepartment;

    /**
     * Constructs a new Career Center Staff with inputs
     * @param userId NTU Account
     * @param username Name of staff
     * @param password Default: password
     * @param staffDepartment Department (ex. CCDS)
     */
    public CareerCenterStaff(String userId, String username, String staffDepartment) {
        super(userId, username);
        this.staffDepartment = staffDepartment;
    }

    /**
     * Retrieves staff department
     * @return String staffDepartment
     */
    public String getStaffDepartment() {
        return staffDepartment;
    }

    /**
     * Sets staff department
     * @param staffDepartment String staffDepartment
     */
    public void setStaffDepartment(String staffDepartment) {
        this.staffDepartment = staffDepartment;
    }

    /**
     * Approves a company representative’s registration request.
     * @param req RegistrationRequest
     */
    public void approveCompanyRep(RegistrationRequest req) {
        Objects.requireNonNull(req, "RegistrationRequest required");
        req.setStatus(RequestStatus.APPROVED);
        req.getRep().setApproved(true);
        System.out.println("Approved company representative: " + req.getRep().getUserName());
    }

    /**
     * Rejects a company representative’s registration request.
     * @param req RegistrationRequest
     */
    public void rejectCompanyRep(RegistrationRequest req) {
        Objects.requireNonNull(req, "RegistrationRequest required");
        req.setStatus(RequestStatus.REJECTED);
        req.getRep().setApproved(false);
        System.out.println("Rejected company representative: " + req.getRep().getUserName());
    }

    /**
     * Approves an internship opportunity.
     * @param opp InternshipOpportunity
     */
    public void approveOpportunity(InternshipOpportunity opp) {
        Objects.requireNonNull(opp, "InternshipOpportunity required");
        opp.setStatus(OpportunityStatus.APPROVED);
        System.out.println("Approved opportunity: " + opp.getTitle());
    }

    /**
     * Rejects an internship opportunity.
     * @param opp InternshipOpportunity
     */
    public void rejectOpportunity(InternshipOpportunity opp) {
        Objects.requireNonNull(opp, "InternshipOpportunity required");
        opp.setStatus(OpportunityStatus.REJECTED);
        System.out.println("Rejected opportunity: " + opp.getTitle());
    }

    /**
     * Decides on a student’s withdrawal request.
     * @param req WithdrawalRequest
     * @param approve Decision to approve or not
     */
    public void decideWithdrawal(WithdrawalRequest req, boolean approve) {
        Objects.requireNonNull(req, "WithdrawalRequest required");
        if (approve) {
            req.setStatus(RequestStatus.APPROVED);
            req.getApplication().setStatus(entity.domain.enums.ApplicationStatus.UNSUCCESSFUL);
            System.out.println("Approved withdrawal request for student: " + req.getRequestedBy().getUserName());
        } else {
            req.setStatus(RequestStatus.REJECTED);
            System.out.println("Rejected withdrawal request for student: " + req.getRequestedBy().getUserName());
        }
    }

    /**
     * Generates a report using the ReportService and a given filter.
     * @param filter ReportFilter filter settings
     * @param reportService ReportService
     * @return Report
     */
    public Report generateReport(ReportFilter filter, ReportService reportService) {
        Objects.requireNonNull(reportService, "ReportService required");
        Report report = reportService.generate(filter);
        System.out.println("Report generated by " + getUserName() + " (" + staffDepartment + ")");
        return report;
    }

    @Override
    public String toString() {
        return String.format("CareerCenterStaff[%s, %s, Dept: %s]",
                getUserId(), getUserName(), staffDepartment);
    }
}
